### POST auth key and permissions
POST http://localhost:8000/key/generate
Content-Type: application/json

[
  {
    "name": "docker_image_limit",
    "value": "500Gb"
  },
  {
    "name": "max_command_private",
    "value": "2"
  }
]
###