default:
    database:
        host: "localhost"
        port: 5432
        username: 'dafunk_builder'
        password: 'dafunk_password'
    broker:
        url: "localhost:9092"
        group: 'Builder',
        num_partitions: 0
        offset_reset: 'latest'
    storage:
        family: "s3"
        bucket: "dafunk"
        region: "eu-west-1"
        access_key: "AKIA3NVLPTX6UUORHIUO"
        secret_key: "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"
test:
    broker:
        url: "localhost:4222"
        group: 'Builder',
        num_partitions: 0
        offset_reset: 'latest'